const List<String> categories = [
  'Books',
  'Business ',
  'Computers',
  'Travel',
  'Sports',
  'Home & Garden',
  '',
];

const List<String> subCategories = [
  'Anthology',
  'Classic',
  'Magical Realism',
  'Fable',
  'Legend',
  'Realistic Fiction',
  'Romance',
  'Short Story',
  'Anthology',
  'Classic',
  'Drama',
  'Fable',
  'Legend',
  'Horror',
  'Romance',
  'Short Story',
  'Anthology',
  'Classic',
  'Drama',
  'Fable',
];

const List<String> subCategoriesImages = [
  'category_image1',
  'category_image2',
  'category_image3',
  'category_image4',
  'category_image5',
  'category_image6',
  'category_image7',
  'category_image8',
  'category_image9',
  'category_image10',
  'category_image11',
  'category_image12',
];

const List<String> subCategoriesTitle = [
  'Tasarım Kanepe',
  'Ottoman Sofa',
  'Booker Cooker',
  'Black Cad',
  'Blue Hope',
  'White Sofa',
  'Tasarım Kanepe',
  'Black Cad',
  'Booker Cooker',
  'White Sofa',
  'Blue Hope',
  'White Sofa',
];
